"""Add unique constraint for name per location per owner

Revision ID: b225026a15be
Revises: 3c55ed48ae81
Create Date: 2025-10-13 22:24:40.329987

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b225026a15be"
down_revision = "3c55ed48ae81"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("filesystem_items", schema=None) as batch_op:
        batch_op.create_unique_constraint("unique_name_per_location_per_owner", ["name", "parent_id", "owner_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("filesystem_items", schema=None) as batch_op:
        batch_op.drop_constraint("unique_name_per_location_per_owner", type_="unique")

    # ### end Alembic commands ###
